In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import plotly.express as px
import glob, os
import seaborn as sns

In [2]:
user_list = glob.glob('Archived users/*.txt')

user_data = []

for user in user_list:
    user_dict = {}
    id = user.split('_')[1].split('.')[0]
    user_dict['id'] = id
    with open(user) as f:
        lines = f.readlines()
        for line in lines:
            line = line.strip()
            key = line.split(': ')[0]
            val = np.nan if len(line.split(': ')) == 1 else line.split(': ')[1]
            user_dict[key] = val
        user_data.append(user_dict)

In [3]:
user_data = pd.DataFrame(user_data)

In [4]:
user_data=user_data.drop(columns=[col for col in user_data.columns if ':' in col])
user_data

,id,Gender,Parkinsons,Tremors,Sided,UPDRS,Impact,Levadopa,DA,MAOB,Other,BirthYear,DiagnosisYear
0,PJU53Y7KVB,Male,True,True,Left,Don't know,Mild,True,False,False,False,NaN,NaN
1,G6OE5CXQPY,Male,False,False,None,Don't know,------,False,False,False,False,1952,------
2,2X17VCRRQA,Male,True,True,Left,Don't know,Severe,True,False,False,False,1951,2003
3,I3U47MF5UF,Female,True,True,None,Don't know,Medium,True,False,False,True,1947,2014
4,L7Q16SJ7KP,Male,True,True,Right,Don't know,Severe,True,False,True,False,1965,2007
...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,VIAXR21TSC,Female,True,True,Left,Don't know,Medium,True,False,False,True,1946,2012
223,IDZHIUK2W2,Female,True,True,None,Don't know,Mild,True,False,False,False,1943,2013
224,SW61HF6XRY,Male,True,True,None,Don't know,Severe,True,False,False,True,1953,2016
225,2JTCBKUP8T,Male,True,True,Right,Don't know,Medium,True,False,False,False,1958,2013
226,LSQWWDXEYO,Male,True,True,Left,Don't know,Mild,False,True,False,False,1951,2016

In [8]:
def is_medicated(df):
    return df['Levadopa'] or df['MAOB'] or df['Other'] or df['DA']

In [9]:
user_data['age'] = 2017 - user_data['BirthYear'].astype(float)
user_data['medicated'] = user_data.apply(is_medicated, axis=1)

In [10]:
user_data

,id,Gender,Parkinsons,Tremors,Sided,UPDRS,Impact,Levadopa,DA,MAOB,Other,BirthYear,DiagnosisYear,age,medicated
0,PJU53Y7KVB,Male,True,True,Left,Don't know,Mild,True,False,False,False,NaN,NaN,NaN,True
1,G6OE5CXQPY,Male,False,False,None,Don't know,------,False,False,False,False,1952,------,65.0,False
2,2X17VCRRQA,Male,True,True,Left,Don't know,Severe,True,False,False,False,1951,2003,66.0,True
3,I3U47MF5UF,Female,True,True,None,Don't know,Medium,True,False,False,True,1947,2014,70.0,True
4,L7Q16SJ7KP,Male,True,True,Right,Don't know,Severe,True,False,True,False,1965,2007,52.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,VIAXR21TSC,Female,True,True,Left,Don't know,Medium,True,False,False,True,1946,2012,71.0,True
223,IDZHIUK2W2,Female,True,True,None,Don't know,Mild,True,False,False,False,1943,2013,74.0,True
224,SW61HF6XRY,Male,True,True,None,Don't know,Severe,True,False,False,True,1953,2016,64.0,True
225,2JTCBKUP8T,Male,True,True,Right,Don't know,Medium,True,False,False,False,1958,2013,59.0,True
226,LSQWWDXEYO,Male,True,True,Left,Don't know,Mild,False,True,False,False,1951,2016,66.0,False